version: '3.7'

services:
  db:
    image: mongo
    ports:
      - "27017:27017"
  app:
    image: kurovale/kuro-paste
#    build: ./
    environment:
      MONGODB_URL: mongodb://db/kuro-paste
      JWT_SECRET: veryVerySecret
    depends_on:
      - db
    ports:
      - "3000:3000"
